import { PropertyAnnotation } from "./AnnotationShapes"
import { hashKey, HashKey } from "./HashKey"
import { StringType } from "@invisit/dynamodb-data-marshaller"

import { autoUUIDAttribute } from "./UUIDAttribute"

export function autoGeneratedHashKey(parameters: Partial<StringType> = {}) {
  return {
    ...autoUUIDAttribute(hashKey(parameters))
  } as Partial<StringType>
}

export function AutoGeneratedHashKey(parameters: Partial<StringType> = {}): PropertyAnnotation {
  return HashKey(autoGeneratedHashKey(parameters))
}
