import { AutoGeneratedHashKey } from './AutoGeneratedHashKey';
import { v4 } from 'uuid';

jest.mock('./Attribute', () => ({Attribute: jest.fn()}));
import { Attribute } from './Attribute';

describe('autoGeneratedHashKey', () => {
    beforeEach(() => {
        (Attribute as any).mockClear();
    });

    it(
        'should call attribute with a defined type, keyType, and defaultProvider',
        () => {
            AutoGeneratedHashKey();

            expect((Attribute as any).mock.calls.length).toBe(1);
            expect((Attribute as any).mock.calls[0]).toEqual([
                {
                    type: 'String',
                    keyType: 'HASH',
                    defaultProvider: v4,
                }
            ]);
        }
    );

    it('should pass through any supplied parameters', () => {
        const attributeName = 'foo'
        AutoGeneratedHashKey({attributeName});

        expect((Attribute as any).mock.calls[0][0])
            .toMatchObject({attributeName});
    });
});
