import {PropertyAnnotation} from './AnnotationShapes';
import {hashKey} from './HashKey';
import {StringType} from '@invisit/dynamodb-data-marshaller';
import {v4} from 'uuid';

export function AutoGeneratedHashKey(
    parameters: Partial<StringType> = {}
): PropertyAnnotation {
    return hashKey({
        ...parameters,
        type: 'String',
        defaultProvider: v4,
    });
}
