"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var ExpressionAttributes_1 = require("./ExpressionAttributes");
var AttributePath_1 = require("./AttributePath");
describe('ExpressionAttributes', function () {
    describe('#addName', function () {
        it('should provide expression-safe aliases for names', function () {
            var e_1, _a;
            var ea = new ExpressionAttributes_1.ExpressionAttributes();
            try {
                for (var DDB_RESERVED_WORDS_1 = tslib_1.__values(DDB_RESERVED_WORDS), DDB_RESERVED_WORDS_1_1 = DDB_RESERVED_WORDS_1.next(); !DDB_RESERVED_WORDS_1_1.done; DDB_RESERVED_WORDS_1_1 = DDB_RESERVED_WORDS_1.next()) {
                    var reservedWord = DDB_RESERVED_WORDS_1_1.value;
                    var alias = ea.addName(reservedWord);
                    expect(alias).toMatch(/^#[A-Za-z0-9]+$/);
                    expect(alias).not.toBe(reservedWord);
                    expect(DDB_RESERVED_WORDS.has(alias)).toBe(false);
                }
            }
            catch (e_1_1) { e_1 = { error: e_1_1 }; }
            finally {
                try {
                    if (DDB_RESERVED_WORDS_1_1 && !DDB_RESERVED_WORDS_1_1.done && (_a = DDB_RESERVED_WORDS_1.return)) _a.call(DDB_RESERVED_WORDS_1);
                }
                finally { if (e_1) throw e_1.error; }
            }
        });
        it('should return the same alias for a name submitted multiple times', function () {
            var e_2, _a;
            var ea = new ExpressionAttributes_1.ExpressionAttributes();
            try {
                for (var DDB_RESERVED_WORDS_2 = tslib_1.__values(DDB_RESERVED_WORDS), DDB_RESERVED_WORDS_2_1 = DDB_RESERVED_WORDS_2.next(); !DDB_RESERVED_WORDS_2_1.done; DDB_RESERVED_WORDS_2_1 = DDB_RESERVED_WORDS_2.next()) {
                    var reservedWord = DDB_RESERVED_WORDS_2_1.value;
                    var alias = ea.addName(reservedWord);
                    for (var i = 0; i < 10; i++) {
                        expect(ea.addName(reservedWord)).toBe(alias);
                    }
                }
            }
            catch (e_2_1) { e_2 = { error: e_2_1 }; }
            finally {
                try {
                    if (DDB_RESERVED_WORDS_2_1 && !DDB_RESERVED_WORDS_2_1.done && (_a = DDB_RESERVED_WORDS_2.return)) _a.call(DDB_RESERVED_WORDS_2);
                }
                finally { if (e_2) throw e_2.error; }
            }
        });
        it('should provide an ExpressionAttributeNameMap of all aliased names', function () {
            var e_3, _a, e_4, _b;
            var ea = new ExpressionAttributes_1.ExpressionAttributes();
            try {
                for (var DDB_RESERVED_WORDS_3 = tslib_1.__values(DDB_RESERVED_WORDS), DDB_RESERVED_WORDS_3_1 = DDB_RESERVED_WORDS_3.next(); !DDB_RESERVED_WORDS_3_1.done; DDB_RESERVED_WORDS_3_1 = DDB_RESERVED_WORDS_3.next()) {
                    var reservedWord = DDB_RESERVED_WORDS_3_1.value;
                    ea.addName(reservedWord);
                }
            }
            catch (e_3_1) { e_3 = { error: e_3_1 }; }
            finally {
                try {
                    if (DDB_RESERVED_WORDS_3_1 && !DDB_RESERVED_WORDS_3_1.done && (_a = DDB_RESERVED_WORDS_3.return)) _a.call(DDB_RESERVED_WORDS_3);
                }
                finally { if (e_3) throw e_3.error; }
            }
            var names = ea.names;
            var reservedWords = new Set(DDB_RESERVED_WORDS);
            try {
                for (var _c = tslib_1.__values(Object.keys(names)), _d = _c.next(); !_d.done; _d = _c.next()) {
                    var expressionSafeName = _d.value;
                    var original = names[expressionSafeName];
                    expect(reservedWords.delete(original)).toBe(true);
                }
            }
            catch (e_4_1) { e_4 = { error: e_4_1 }; }
            finally {
                try {
                    if (_d && !_d.done && (_b = _c.return)) _b.call(_c);
                }
                finally { if (e_4) throw e_4.error; }
            }
            expect(reservedWords.size).toBe(0);
        });
        it('should allow the addition of list index dereferences', function () {
            var attributes = new ExpressionAttributes_1.ExpressionAttributes();
            attributes.addName(new AttributePath_1.AttributePath('foo[2]'));
            expect(attributes.names).toEqual({
                '#attr0': 'foo',
            });
        });
        it('should allow the addition of nested attributes', function () {
            var attributes = new ExpressionAttributes_1.ExpressionAttributes();
            attributes.addName(new AttributePath_1.AttributePath('foo.bar'));
            expect(attributes.names).toEqual({
                '#attr0': 'foo',
                '#attr1': 'bar',
            });
        });
        it('should allow the nesting of complex attributes to an arbitrary depth', function () {
            var attributes = new ExpressionAttributes_1.ExpressionAttributes();
            attributes.addName(new AttributePath_1.AttributePath('foo.bar[3].baz[4].quux.snap.crackle.pop[2][1][0]'));
            expect(attributes.names).toEqual({
                '#attr0': 'foo',
                '#attr1': 'bar',
                '#attr2': 'baz',
                '#attr3': 'quux',
                '#attr4': 'snap',
                '#attr5': 'crackle',
                '#attr6': 'pop',
            });
        });
    });
    describe('#addValue', function () {
        it('should provide expression-safe aliases for values', function () {
            var e_5, _a;
            var ea = new ExpressionAttributes_1.ExpressionAttributes();
            try {
                for (var DDB_RESERVED_WORDS_4 = tslib_1.__values(DDB_RESERVED_WORDS), DDB_RESERVED_WORDS_4_1 = DDB_RESERVED_WORDS_4.next(); !DDB_RESERVED_WORDS_4_1.done; DDB_RESERVED_WORDS_4_1 = DDB_RESERVED_WORDS_4.next()) {
                    var reservedWord = DDB_RESERVED_WORDS_4_1.value;
                    var alias = ea.addValue(reservedWord);
                    expect(alias).toMatch(/^:[A-Za-z0-9]+$/);
                }
            }
            catch (e_5_1) { e_5 = { error: e_5_1 }; }
            finally {
                try {
                    if (DDB_RESERVED_WORDS_4_1 && !DDB_RESERVED_WORDS_4_1.done && (_a = DDB_RESERVED_WORDS_4.return)) _a.call(DDB_RESERVED_WORDS_4);
                }
                finally { if (e_5) throw e_5.error; }
            }
        });
        it('should provide an ExpressionAttributeValueMap of all aliased values', function () {
            var e_6, _a;
            var expected = {};
            var ea = new ExpressionAttributes_1.ExpressionAttributes();
            try {
                for (var _b = tslib_1.__values(tslib_1.__spread(DDB_RESERVED_WORDS)), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var reservedWord = _c.value;
                    var alias = ea.addValue(reservedWord);
                    expected[alias] = { S: reservedWord };
                }
            }
            catch (e_6_1) { e_6 = { error: e_6_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_6) throw e_6.error; }
            }
            expect(ea.values).toEqual(expected);
        });
    });
});
var DDB_RESERVED_WORDS = new Set([
    'ABORT',
    'ABSOLUTE',
    'ACTION',
    'ADD',
    'AFTER',
    'AGENT',
    'AGGREGATE',
    'ALL',
    'ALLOCATE',
    'ALTER',
    'ANALYZE',
    'AND',
    'ANY',
    'ARCHIVE',
    'ARE',
    'ARRAY',
    'AS',
    'ASC',
    'ASCII',
    'ASENSITIVE',
    'ASSERTION',
    'ASYMMETRIC',
    'AT',
    'ATOMIC',
    'ATTACH',
    'ATTRIBUTE',
    'AUTH',
    'AUTHORIZATION',
    'AUTHORIZE',
    'AUTO',
    'AVG',
    'BACK',
    'BACKUP',
    'BASE',
    'BATCH',
    'BEFORE',
    'BEGIN',
    'BETWEEN',
    'BIGINT',
    'BINARY',
    'BIT',
    'BLOB',
    'BLOCK',
    'BOOLEAN',
    'BOTH',
    'BREADTH',
    'BUCKET',
    'BULK',
    'BY',
    'BYTE',
    'CALL',
    'CALLED',
    'CALLING',
    'CAPACITY',
    'CASCADE',
    'CASCADED',
    'CASE',
    'CAST',
    'CATALOG',
    'CHAR',
    'CHARACTER',
    'CHECK',
    'CLASS',
    'CLOB',
    'CLOSE',
    'CLUSTER',
    'CLUSTERED',
    'CLUSTERING',
    'CLUSTERS',
    'COALESCE',
    'COLLATE',
    'COLLATION',
    'COLLECTION',
    'COLUMN',
    'COLUMNS',
    'COMBINE',
    'COMMENT',
    'COMMIT',
    'COMPACT',
    'COMPILE',
    'COMPRESS',
    'CONDITION',
    'CONFLICT',
    'CONNECT',
    'CONNECTION',
    'CONSISTENCY',
    'CONSISTENT',
    'CONSTRAINT',
    'CONSTRAINTS',
    'CONSTRUCTOR',
    'CONSUMED',
    'CONTINUE',
    'CONVERT',
    'COPY',
    'CORRESPONDING',
    'COUNT',
    'COUNTER',
    'CREATE',
    'CROSS',
    'CUBE',
    'CURRENT',
    'CURSOR',
    'CYCLE',
    'DATA',
    'DATABASE',
    'DATE',
    'DATETIME',
    'DAY',
    'DEALLOCATE',
    'DEC',
    'DECIMAL',
    'DECLARE',
    'DEFAULT',
    'DEFERRABLE',
    'DEFERRED',
    'DEFINE',
    'DEFINED',
    'DEFINITION',
    'DELETE',
    'DELIMITED',
    'DEPTH',
    'DEREF',
    'DESC',
    'DESCRIBE',
    'DESCRIPTOR',
    'DETACH',
    'DETERMINISTIC',
    'DIAGNOSTICS',
    'DIRECTORIES',
    'DISABLE',
    'DISCONNECT',
    'DISTINCT',
    'DISTRIBUTE',
    'DO',
    'DOMAIN',
    'DOUBLE',
    'DROP',
    'DUMP',
    'DURATION',
    'DYNAMIC',
    'EACH',
    'ELEMENT',
    'ELSE',
    'ELSEIF',
    'EMPTY',
    'ENABLE',
    'END',
    'EQUAL',
    'EQUALS',
    'ERROR',
    'ESCAPE',
    'ESCAPED',
    'EVAL',
    'EVALUATE',
    'EXCEEDED',
    'EXCEPT',
    'EXCEPTION',
    'EXCEPTIONS',
    'EXCLUSIVE',
    'EXEC',
    'EXECUTE',
    'EXISTS',
    'EXIT',
    'EXPLAIN',
    'EXPLODE',
    'EXPORT',
    'EXPRESSION',
    'EXTENDED',
    'EXTERNAL',
    'EXTRACT',
    'FAIL',
    'FALSE',
    'FAMILY',
    'FETCH',
    'FIELDS',
    'FILE',
    'FILTER',
    'FILTERING',
    'FINAL',
    'FINISH',
    'FIRST',
    'FIXED',
    'FLATTERN',
    'FLOAT',
    'FOR',
    'FORCE',
    'FOREIGN',
    'FORMAT',
    'FORWARD',
    'FOUND',
    'FREE',
    'FROM',
    'FULL',
    'FUNCTION',
    'FUNCTIONS',
    'GENERAL',
    'GENERATE',
    'GET',
    'GLOB',
    'GLOBAL',
    'GO',
    'GOTO',
    'GRANT',
    'GREATER',
    'GROUP',
    'GROUPING',
    'HANDLER',
    'HASH',
    'HAVE',
    'HAVING',
    'HEAP',
    'HIDDEN',
    'HOLD',
    'HOUR',
    'IDENTIFIED',
    'IDENTITY',
    'IF',
    'IGNORE',
    'IMMEDIATE',
    'IMPORT',
    'IN',
    'INCLUDING',
    'INCLUSIVE',
    'INCREMENT',
    'INCREMENTAL',
    'INDEX',
    'INDEXED',
    'INDEXES',
    'INDICATOR',
    'INFINITE',
    'INITIALLY',
    'INLINE',
    'INNER',
    'INNTER',
    'INOUT',
    'INPUT',
    'INSENSITIVE',
    'INSERT',
    'INSTEAD',
    'INT',
    'INTEGER',
    'INTERSECT',
    'INTERVAL',
    'INTO',
    'INVALIDATE',
    'IS',
    'ISOLATION',
    'ITEM',
    'ITEMS',
    'ITERATE',
    'JOIN',
    'KEY',
    'KEYS',
    'LAG',
    'LANGUAGE',
    'LARGE',
    'LAST',
    'LATERAL',
    'LEAD',
    'LEADING',
    'LEAVE',
    'LEFT',
    'LENGTH',
    'LESS',
    'LEVEL',
    'LIKE',
    'LIMIT',
    'LIMITED',
    'LINES',
    'LIST',
    'LOAD',
    'LOCAL',
    'LOCALTIME',
    'LOCALTIMESTAMP',
    'LOCATION',
    'LOCATOR',
    'LOCK',
    'LOCKS',
    'LOG',
    'LOGED',
    'LONG',
    'LOOP',
    'LOWER',
    'MAP',
    'MATCH',
    'MATERIALIZED',
    'MAX',
    'MAXLEN',
    'MEMBER',
    'MERGE',
    'METHOD',
    'METRICS',
    'MIN',
    'MINUS',
    'MINUTE',
    'MISSING',
    'MOD',
    'MODE',
    'MODIFIES',
    'MODIFY',
    'MODULE',
    'MONTH',
    'MULTI',
    'MULTISET',
    'NAME',
    'NAMES',
    'NATIONAL',
    'NATURAL',
    'NCHAR',
    'NCLOB',
    'NEW',
    'NEXT',
    'NO',
    'NONE',
    'NOT',
    'NULL',
    'NULLIF',
    'NUMBER',
    'NUMERIC',
    'OBJECT',
    'OF',
    'OFFLINE',
    'OFFSET',
    'OLD',
    'ON',
    'ONLINE',
    'ONLY',
    'OPAQUE',
    'OPEN',
    'OPERATOR',
    'OPTION',
    'OR',
    'ORDER',
    'ORDINALITY',
    'OTHER',
    'OTHERS',
    'OUT',
    'OUTER',
    'OUTPUT',
    'OVER',
    'OVERLAPS',
    'OVERRIDE',
    'OWNER',
    'PAD',
    'PARALLEL',
    'PARAMETER',
    'PARAMETERS',
    'PARTIAL',
    'PARTITION',
    'PARTITIONED',
    'PARTITIONS',
    'PATH',
    'PERCENT',
    'PERCENTILE',
    'PERMISSION',
    'PERMISSIONS',
    'PIPE',
    'PIPELINED',
    'PLAN',
    'POOL',
    'POSITION',
    'PRECISION',
    'PREPARE',
    'PRESERVE',
    'PRIMARY',
    'PRIOR',
    'PRIVATE',
    'PRIVILEGES',
    'PROCEDURE',
    'PROCESSED',
    'PROJECT',
    'PROJECTION',
    'PROPERTY',
    'PROVISIONING',
    'PUBLIC',
    'PUT',
    'QUERY',
    'QUIT',
    'QUORUM',
    'RAISE',
    'RANDOM',
    'RANGE',
    'RANK',
    'RAW',
    'READ',
    'READS',
    'REAL',
    'REBUILD',
    'RECORD',
    'RECURSIVE',
    'REDUCE',
    'REF',
    'REFERENCE',
    'REFERENCES',
    'REFERENCING',
    'REGEXP',
    'REGION',
    'REINDEX',
    'RELATIVE',
    'RELEASE',
    'REMAINDER',
    'RENAME',
    'REPEAT',
    'REPLACE',
    'REQUEST',
    'RESET',
    'RESIGNAL',
    'RESOURCE',
    'RESPONSE',
    'RESTORE',
    'RESTRICT',
    'RESULT',
    'RETURN',
    'RETURNING',
    'RETURNS',
    'REVERSE',
    'REVOKE',
    'RIGHT',
    'ROLE',
    'ROLES',
    'ROLLBACK',
    'ROLLUP',
    'ROUTINE',
    'ROW',
    'ROWS',
    'RULE',
    'RULES',
    'SAMPLE',
    'SATISFIES',
    'SAVE',
    'SAVEPOINT',
    'SCAN',
    'SCHEMA',
    'SCOPE',
    'SCROLL',
    'SEARCH',
    'SECOND',
    'SECTION',
    'SEGMENT',
    'SEGMENTS',
    'SELECT',
    'SELF',
    'SEMI',
    'SENSITIVE',
    'SEPARATE',
    'SEQUENCE',
    'SERIALIZABLE',
    'SESSION',
    'SET',
    'SETS',
    'SHARD',
    'SHARE',
    'SHARED',
    'SHORT',
    'SHOW',
    'SIGNAL',
    'SIMILAR',
    'SIZE',
    'SKEWED',
    'SMALLINT',
    'SNAPSHOT',
    'SOME',
    'SOURCE',
    'SPACE',
    'SPACES',
    'SPARSE',
    'SPECIFIC',
    'SPECIFICTYPE',
    'SPLIT',
    'SQL',
    'SQLCODE',
    'SQLERROR',
    'SQLEXCEPTION',
    'SQLSTATE',
    'SQLWARNING',
    'START',
    'STATE',
    'STATIC',
    'STATUS',
    'STORAGE',
    'STORE',
    'STORED',
    'STREAM',
    'STRING',
    'STRUCT',
    'STYLE',
    'SUB',
    'SUBMULTISET',
    'SUBPARTITION',
    'SUBSTRING',
    'SUBTYPE',
    'SUM',
    'SUPER',
    'SYMMETRIC',
    'SYNONYM',
    'SYSTEM',
    'TABLE',
    'TABLESAMPLE',
    'TEMP',
    'TEMPORARY',
    'TERMINATED',
    'TEXT',
    'THAN',
    'THEN',
    'THROUGHPUT',
    'TIME',
    'TIMESTAMP',
    'TIMEZONE',
    'TINYINT',
    'TO',
    'TOKEN',
    'TOTAL',
    'TOUCH',
    'TRAILING',
    'TRANSACTION',
    'TRANSFORM',
    'TRANSLATE',
    'TRANSLATION',
    'TREAT',
    'TRIGGER',
    'TRIM',
    'TRUE',
    'TRUNCATE',
    'TTL',
    'TUPLE',
    'TYPE',
    'UNDER',
    'UNDO',
    'UNION',
    'UNIQUE',
    'UNIT',
    'UNKNOWN',
    'UNLOGGED',
    'UNNEST',
    'UNPROCESSED',
    'UNSIGNED',
    'UNTIL',
    'UPDATE',
    'UPPER',
    'URL',
    'USAGE',
    'USE',
    'USER',
    'USERS',
    'USING',
    'UUID',
    'VACUUM',
    'VALUE',
    'VALUED',
    'VALUES',
    'VARCHAR',
    'VARIABLE',
    'VARIANCE',
    'VARINT',
    'VARYING',
    'VIEW',
    'VIEWS',
    'VIRTUAL',
    'VOID',
    'WAIT',
    'WHEN',
    'WHENEVER',
    'WHERE',
    'WHILE',
    'WINDOW',
    'WITH',
    'WITHIN',
    'WITHOUT',
    'WORK',
    'WRAPPED',
    'WRITE',
    'YEAR',
    'ZONE',
]);
//# sourceMappingURL=ExpressionAttributes.spec.js.map